name: AntiHaxerman
version: 3.0
main: me.tecnio.antihaxerman.AntiHaxermanPlugin
authors: [Tecnio]
description: AntiHaxerman AntiCheat
load: STARTUP
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion

commands:
  antihaxerman:
    description: Commands for AntiHaxerman Anticheat.
    usage: /antihaxerman
    aliases: [ahm]
    permission: antihaxerman.commands
  alerts:
    description: Toggles alerts for AntiHaxerman Anticheat.
    usage: /alerts
    permission: antihaxerman.alerts
