name: AntiHaxerman
version: 4.0
main: me.tecnio.antihaxerman.AntiHaxermanPlugin
authors: [Tecnio]
description: AntiHaxerman AntiCheat

commands:
  antihaxerman:
    description: Commands for AntiHaxerman Anticheat.
    usage: /antihaxerman
    aliases: [ahm]
    permission: antihaxerman.commands
  verus:
    description: Funny
    usage: /verus
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - Geyser-Spigot