name: AntiHaxerman
version: 1.0-PRE
author: Tecnio
main: me.tecnio.antihaxerman.AntiHaxerPlugin
load: STARTUP

commands:
  antihaxerman:
    description: Base command for AntiHaxerman.
    usage: /<command>
    permission: antihaxerman.command
    permission-message: "No permission."